# Site settings
title: Babies.MX
email: contacto@babies.mx
description: > # this means to ignore newlines until "baseurl:"
  Todo acerca de tu bebé
baseurl: "/blog/" # the subpath of your site, e.g. /blog/
url: "http://www.babies.mx" # the base hostname & protocol for your site
twitter_username: babiesmx
github_username:

# Build settings
markdown: kramdown
